version:  '3'
services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
        - '3000:3000'
  cpnginx-reverse-proxy:
    ports:
      - '80:80'
    ipc: host
    image: checkpoint/cloudguard-appsec-standalone
    volumes:
      - ./cpnginx-reverse-proxy/default:/etc/nginx/conf.d/default.conf
      - ./cpnginx-reverse-proxy/data:/etc/cp/data
      - ./cpnginx-reverse-proxy/conf:/etc/cp/conf
      - ./cpnginx-reverse-proxy/logs:/var/log/nano_agent
      - ./cpnginx-reverse-proxy/logs:/var/log/nano_agent     
    command: ["/cp-nano-agent", "--token", "$TOKEN"]
