version:  '3.9'
services:
  nginx-reverse-proxy:
    ports:
      - '80:80'
      - '443:443'
      - '8117:8117'
    image: checkpoint/cloudguard-appsec-standalone:latest
    networks:
      - tier1
    volumes:
      - nginx_data:/etc/nginx/conf.d/
      - ssl_data:/etc/certs/
      - agent_data:/etc/cp/data
      - agent_conf:/etc/cp/conf
      - agent_logs:/var/log/nano_agent
    command: ["/cloudguard-appsec-standalone", "--token", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
    restart: always
